name: collaboration_career
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.2
  - r-tidyverse
  - r-dplyr
  - r-stringr
  - r-readr
  - r-readxl
  - r-igraph
  - r-sna
  - r-asnipe
  - r-network
  - r-intergraph
  - r-reshape2
  - r-plyr
  - r-ggplot2
  - r-gridextra
  - r-qpcR
  - r-lme4
  - r-knitr
  - r-rmarkdown
