#!/bin/bash
R -e "install.packages('bibliometrix', repos='http://cran.r-project.org')"
R -e "install.packages('rscopus', repos='http://cran.r-project.org')"
R -e "install.packages('jtools', repos='http://cran.r-project.org')"
R -e "install.packages('rowr', repos='http://cran.r-project.org')"
